Finished 02-components part
js-tasks-ru/vue-20201210_aleksandr5 pull request #2
Opened 2020-12-18 23:13 UTC by alex-milyaev1991

2020-12-18 23:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
MeetupPageComponent
+ MeetupPage должен быть определён
+ MeetupView должен иметь обязательный параметр meetup с объектом митапа
+ MeetupView должен показывать изображение, описание, информацию и программу митапа соответствующими компонентами
+ MeetupCover не должен удалять изображение по умолчанию в случае отсутствия ссылки на изображение
+ MeetupCover должен выводить название митапа
+ MeetupDescription должен выводить описание митапа
+ MeetupAgenda должен иметь параметр массив agenda
+ MeetupAgenda должен выводить программу через компоненты MeetupAgendaItem
- MeetupCover должен иметь необязательные строковые параметры link и title
- MeetupCover должен выводить изображение митапа
- MeetupDescription должен иметь необязательный строковый параметр description
- MeetupInfo должен иметь обязательные строковые параметры organizer, place и обязательный параметр с датой date
- MeetupInfo должен выводить краткое описание митапа
- MeetupAgendaItem должен иметь обязательный параметр объект agendaItem
- MeetupAgendaItem должен выводить время
- MeetupAgendaItem должен выводить заголовок по умолчанию
- MeetupAgendaItem должен выводить правильную иконку для регистрации
- MeetupAgendaItem должен выводить доклад
```
```diff
MeetupsCalendar
+ MeetupsCalendar должен вывести 5 строк по 7 дней для апреля 2020
+ MeetupsCalendar должен вывести только первые два и последние три дня для апреля 2020 неактивными
+ MeetupsCalendar должен вывести правильные числа для апреля 2020
+ MeetupsCalendar должен показать митапы 12 мая после перехода на следующий месяц с апреля 2020
- MeetupsCalendar должен иметь обязательный параметр meetups по списком митапов
- MeetupsCalendar должен локализовано месяц и год в заголовке для апреля 2020
- MeetupsCalendar должен вывести май 2020
- MeetupsCalendar должен вывести июнь 2020
- MeetupsCalendar должен показать февраль 2021 после 10 кликов на след. месяц с апреля 2020
- MeetupsCalendar должен показать февраль 2021 после 9 кликов на след. месяц с 31 мая 2020
- MeetupsCalendar должен показать ноябрь 2019 после 5 кликов на пред. месяц с апреля 2020
```
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
- CounterButton должен рендерить кнопку с текстом count
- CounterButton должен иметь count 0 по умолчанию
```

2020-12-19 10:25 UTC, ShGKme requested changes
Задача не проходит тестирование

2020-12-19 10:25 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +      // по этому хотя мы явно и не передаем props value и не емитим собыие input это будет делаться автоматически
По умолчанию v-model работает на параметр value и событие input, да.
Но это поведение настраивается свойством `model`.

В этой задаче требуется сделать именно так, не добавляя дублирующего параметра и события.

https://vuejs.org/v2/guide/components-custom-events.html#Customizing-Component-v-model

2020-12-19 10:25 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
Если создавать локальную копию входного параметра, то требуется дополнительно отслеживать изменение входного параметра. После того, как компонент создался, и был инициализирован `number` возможно, что родитель передаст новое значение в `count`, например, сбросит его. В вашем решении кнопка на это не отреагирует...

Иметь локальное состояние в этой задаче вообще не требуется. Достаточно сообщить родителю о том, что произошло увеличение, и с событием отправить новое значения (не меняя его, только передать результат вычисления).

2020-12-19 10:25 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupAgenda.js
> +      default: () => {}
Эта функция default ничего не делает и ничего не возвращает...
Если хотелось вернуть пустой объект, то требовалось добавить скобочки: `() => ({})`.
Но и возвращать пустой объект тут странно, так как расписание - это массив: `() => []`.

2020-12-19 10:25 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupInfo.js
> +        <time :datetime="dateMeetup.number">{{ dateMeetup.string | uppercase }}</time>
Фильтры deprecated. Они удалены в Vue 3. Лучше уже сейчас ими не пользоваться.
Их можно заменить на вызов метода, или вычисляемое свойство. В будущем можно будет заменить на Pipeline Operator [Stage 2 Proposal](https://github.com/tc39/proposal-pipeline-operator).

2020-12-19 10:25 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupInfo.js
> +        <time :datetime="dateMeetup.number">{{ dateMeetup.string | uppercase }}</time>
И не совсем понял, зачем здесь этот фильтр...

2020-12-19 10:25 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupPage.js
> +      meetup: {}
На вебинаре мы начальным значением массива устанавливали пустой массив. Это корректно, пустой массив митапов - это частный случай массива митапов. Но пустой объект - не частный случай объекта с описанием митапа. Хотя установка начального значения в {} избавляет от простых ошибок, она не избавляет от ошибок полностью, оставляя более трудно-находимые ошибки. Лучше начальным значением указать null и делать проверки. Например, сейчас на время загрузки митапа отображается "сломанная" страница с пустыми значениями.

Проверки нужны в двух местах: в вычисляемых свойствах, чтобы не было обращений к свойствам у `null`, и где-нибудь на верхнем уровне в шаблоне с `v-if`, чтобы не выводить страницу с данными митапа, пока нет данных митапа. В случае, когда все вычисляемые свойства уже находятся внутри `<meetup-view>`, достаточно просто не выводить вообще компонент митапом MeetupView, пока данные митапа не пришли (так же, через `v-if`).

2020-12-19 10:25 UTC, ShGKme commented on 02-components/03-MeetupsCalendar/MeetupsCalendar.js
> +          <div>{{ monthName }} 2020</div>
А если долистать до следующего года? :)

2020-12-19 10:25 UTC, ShGKme commented on 02-components/03-MeetupsCalendar/data.js
> +]
Эти значения никогда не требуется хранить в коде. Они все получаются из API браузера для выбранной пользователем локали. Для этого можно использовать модуль `Intl` или методы даты, например, `.toLocalDateString()` и их параметры.

2020-12-19 10:25 UTC, ShGKme commented on 02-components/03-MeetupsCalendar/MeetupsCalendar.js
> +    this.days = this.daysInMonth(this.currentMonth, this.currentYear)
Подобную инициализацию лучше делать сразу при вычислении начального состояния компонента в `data()`, чтобы инициализация была синхронной. Функция created сработает асинхронно, как обработчик события, когда компонент уже прошёл часть инициализации.

2020-12-19 10:25 UTC, ShGKme commented on 02-components/03-MeetupsCalendar/MeetupsCalendar.js
> +    },
Это лучше сделать вычисляемым свойством, так как значение вычисляется из текущего месяца и года

2020-12-19 10:25 UTC, ShGKme commented on 02-components/03-MeetupsCalendar/MeetupsCalendar.js
> +      this.days = this.daysInMonth(this.currentMonth, this.currentYear)
Аналогично с днями - лучше сделать вычисляемым свойством.

2020-12-19 10:58 UTC, ShGKme commented on 02-components/02-MeetupPageComponent/MeetupInfo.js
> +  },
Здесь также требуется использовать возможности локализации браузера, а не формировать дату самостоятельно.

2020-12-25 19:42 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
MeetupPageComponent
+ MeetupPage должен быть определён
+ MeetupView должен иметь обязательный параметр meetup с объектом митапа
+ MeetupView должен показывать изображение, описание, информацию и программу митапа соответствующими компонентами
+ MeetupCover должен иметь необязательные строковые параметры link и title
+ MeetupCover должен выводить изображение митапа
+ MeetupCover не должен удалять изображение по умолчанию в случае отсутствия ссылки на изображение
+ MeetupCover должен выводить название митапа
+ MeetupDescription должен иметь необязательный строковый параметр description
+ MeetupDescription должен выводить описание митапа
+ MeetupInfo должен иметь обязательные строковые параметры organizer, place и обязательный параметр с датой date
+ MeetupInfo должен выводить краткое описание митапа
+ MeetupAgenda должен иметь параметр массив agenda
+ MeetupAgenda должен выводить программу через компоненты MeetupAgendaItem
+ MeetupAgendaItem должен иметь обязательный параметр объект agendaItem
+ MeetupAgendaItem должен выводить время
+ MeetupAgendaItem должен выводить заголовок по умолчанию
+ MeetupAgendaItem должен выводить правильную иконку для регистрации
+ MeetupAgendaItem должен выводить доклад
```
```diff
MeetupsCalendar
+ MeetupsCalendar должен иметь обязательный параметр meetups по списком митапов
+ MeetupsCalendar должен вывести 5 строк по 7 дней для апреля 2020
+ MeetupsCalendar должен вывести только первые два и последние три дня для апреля 2020 неактивными
+ MeetupsCalendar должен вывести правильные числа для апреля 2020
+ MeetupsCalendar должен показать митапы 12 мая после перехода на следующий месяц с апреля 2020
- MeetupsCalendar должен локализовано месяц и год в заголовке для апреля 2020
- MeetupsCalendar должен вывести май 2020
- MeetupsCalendar должен вывести июнь 2020
- MeetupsCalendar должен показать февраль 2021 после 10 кликов на след. месяц с апреля 2020
- MeetupsCalendar должен показать февраль 2021 после 9 кликов на след. месяц с 31 мая 2020
- MeetupsCalendar должен показать ноябрь 2019 после 5 кликов на пред. месяц с апреля 2020
```
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен иметь count 0 по умолчанию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```

2020-12-25 21:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
MeetupPageComponent
+ MeetupPage должен быть определён
+ MeetupView должен иметь обязательный параметр meetup с объектом митапа
+ MeetupView должен показывать изображение, описание, информацию и программу митапа соответствующими компонентами
+ MeetupCover должен иметь необязательные строковые параметры link и title
+ MeetupCover должен выводить изображение митапа
+ MeetupCover не должен удалять изображение по умолчанию в случае отсутствия ссылки на изображение
+ MeetupCover должен выводить название митапа
+ MeetupDescription должен иметь необязательный строковый параметр description
+ MeetupDescription должен выводить описание митапа
+ MeetupInfo должен иметь обязательные строковые параметры organizer, place и обязательный параметр с датой date
+ MeetupInfo должен выводить краткое описание митапа
+ MeetupAgenda должен иметь параметр массив agenda
+ MeetupAgenda должен выводить программу через компоненты MeetupAgendaItem
+ MeetupAgendaItem должен иметь обязательный параметр объект agendaItem
+ MeetupAgendaItem должен выводить время
+ MeetupAgendaItem должен выводить заголовок по умолчанию
+ MeetupAgendaItem должен выводить правильную иконку для регистрации
+ MeetupAgendaItem должен выводить доклад
```
```diff
MeetupsCalendar
+ MeetupsCalendar должен иметь обязательный параметр meetups по списком митапов
+ MeetupsCalendar должен вывести 5 строк по 7 дней для апреля 2020
+ MeetupsCalendar должен вывести только первые два и последние три дня для апреля 2020 неактивными
+ MeetupsCalendar должен вывести правильные числа для апреля 2020
+ MeetupsCalendar должен локализовано месяц и год в заголовке для апреля 2020
+ MeetupsCalendar должен вывести май 2020
+ MeetupsCalendar должен вывести июнь 2020
+ MeetupsCalendar должен показать февраль 2021 после 10 кликов на след. месяц с апреля 2020
+ MeetupsCalendar должен показать ноябрь 2019 после 5 кликов на пред. месяц с апреля 2020
+ MeetupsCalendar должен показать митапы 12 мая после перехода на следующий месяц с апреля 2020
- MeetupsCalendar должен показать февраль 2021 после 9 кликов на след. месяц с 31 мая 2020
```
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен иметь count 0 по умолчанию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```

2020-12-25 21:41 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
MeetupPageComponent
+ MeetupPage должен быть определён
+ MeetupView должен иметь обязательный параметр meetup с объектом митапа
+ MeetupView должен показывать изображение, описание, информацию и программу митапа соответствующими компонентами
+ MeetupCover должен иметь необязательные строковые параметры link и title
+ MeetupCover должен выводить изображение митапа
+ MeetupCover не должен удалять изображение по умолчанию в случае отсутствия ссылки на изображение
+ MeetupCover должен выводить название митапа
+ MeetupDescription должен иметь необязательный строковый параметр description
+ MeetupDescription должен выводить описание митапа
+ MeetupInfo должен иметь обязательные строковые параметры organizer, place и обязательный параметр с датой date
+ MeetupInfo должен выводить краткое описание митапа
+ MeetupAgenda должен иметь параметр массив agenda
+ MeetupAgenda должен выводить программу через компоненты MeetupAgendaItem
+ MeetupAgendaItem должен иметь обязательный параметр объект agendaItem
+ MeetupAgendaItem должен выводить время
+ MeetupAgendaItem должен выводить заголовок по умолчанию
+ MeetupAgendaItem должен выводить правильную иконку для регистрации
+ MeetupAgendaItem должен выводить доклад
```
```diff
MeetupsCalendar
+ MeetupsCalendar должен иметь обязательный параметр meetups по списком митапов
+ MeetupsCalendar должен вывести 5 строк по 7 дней для апреля 2020
+ MeetupsCalendar должен вывести только первые два и последние три дня для апреля 2020 неактивными
+ MeetupsCalendar должен вывести правильные числа для апреля 2020
+ MeetupsCalendar должен локализовано месяц и год в заголовке для апреля 2020
+ MeetupsCalendar должен вывести май 2020
+ MeetupsCalendar должен вывести июнь 2020
+ MeetupsCalendar должен показать февраль 2021 после 10 кликов на след. месяц с апреля 2020
+ MeetupsCalendar должен показать февраль 2021 после 9 кликов на след. месяц с 31 мая 2020
+ MeetupsCalendar должен показать ноябрь 2019 после 5 кликов на пред. месяц с апреля 2020
+ MeetupsCalendar должен показать митапы 12 мая после перехода на следующий месяц с апреля 2020
```
```diff
Компонент CounterButton
+ CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
+ CounterButton должен рендерить кнопку с текстом count
+ CounterButton должен иметь count 0 по умолчанию
+ CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-12-25 21:43 UTC, ShGKme approved these changes
Принято, но с небольшими замечаниями

2020-12-25 21:43 UTC, ShGKme commented on 02-components/03-MeetupsCalendar/MeetupsCalendar.js
> +    default: () => []
Здесь default описан, как отдельный параметр, а не как свойство параметра meetups...
При этом указывать значение по умолчанию для обязательных параметров нет смысла, так как они обязательные, и в них требуется передавать значение.

2020-12-25 21:44 UTC, merged